[package]
name = "isha256"
version = "0.1.0"
authors = ["Nym Seddon <unseddd@shh.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
